### ISSUE TITLE
Team section looks bad on iphone safari and other mobile devices breakpoints

### ISSUE THREAD

**Issue by ryanmmmmm** [UnFederalReserve/unfederalreserve.com#4]

**Comment by ryanmmmmm** [comment]
![2021-01-24 13 33 18](https://user-images.githubusercontent.com/705959/106031128-ba72cc80-6083-11eb-96a6-4d30122b6f12.jpg)

**Comment by vladyslav2** [comment]
@ryanmmmmm thats already fixed
